CREATE TABLE chat_room_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'PENDING',
    nickname VARCHAR NOT NULL,
    profile_image_url VARCHAR,
    profile_image_public_id VARCHAR,
    requested_at TIMESTAMPTZ NOT NULL,
    assigned_user_id BIGINT,
    CONSTRAINT fk_join_requests_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_join_requests_assigned_user FOREIGN KEY (assigned_user_id) REFERENCES users (id),
    CONSTRAINT ck_join_requests_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

CREATE INDEX idx_join_requests_chat_room_status_requested_at
    ON chat_room_join_requests (chat_room_id, status, requested_at);
